apiVersion: v1
name: chart-hotscan
version: 1.0.0
kubeVersion: 
description: helm deployment of hotscan browser application
keywords:
  - hotscan
  - scanning
maintainers:
  - name: Probhonjon Baruah
    email: probhonjonbaruah@gmail.com
    url: https://bigfoot31.github.io
engine: gotpl
appVersion: 8.5.0
deprecated: false
tillerVersion: ">=2.1.0"
