
apiVersion: {{ .Chart.ApiVersion }}
kind: Service
metadata:
  name: elasticsearch-master-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels.master }}
    {{ . }}{{ end }}
spec:
  selector:
    {{- range .Values.labels.master }}
    {{ . }}{{ end }}
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  type: {{ .Values.elasticsearch.serviceType.master | default "None" }}
  clusterIP: None
