
apiVersion: {{ .Chart.ApiVersion }}
kind: ConfigMap
metadata:
  name: elasticsearch- {{- .Chart.AppVersion }}
  namespace: {{ .Values.global.namespace }}
data: 
  master: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    discovery.zen:
      minimum_master_nodes: {{ .Values.elasticsearch.min_master }}
      ping.unicast.hosts: elasticsearch-master-svc.elkstack.svc.cluster.local:9300
    network.host: _eth0_
    node:
      master: true
      data: false
      ingest: false
      ml: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
  data: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    discovery.zen:
      minimum_master_nodes: {{ .Values.elasticsearch.min_master }}
      ping.unicast.hosts: elasticsearch-master-svc.elkstack.svc.cluster.local:9300
    network.host: 0.0.0.0
    node:
      master: false
      data: true
      ingest: true
      ml: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
