
apiVersion: {{ .Chart.ApiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.services.kibana }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
spec:
  ports:
  - name: kibana-svc-port
    port: {{ .Values.global.ports.kibana.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.global.ports.kibana.containerPort }}
    nodePort: {{ .Values.global.ports.kibana.nodePort }}
  selector:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
  type: {{ .Values.serviceType | default "NodePort" }}

