
apiVersion: {{ .Chart.ApiVersion }}
kind: ConfigMap
metadata:
  name: kibana- {{- .Chart.AppVersion }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
data:
  kibana: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: "http://elasticsearch-data-svc. {{- .Values.global.namespace -}} .svc.cluster.local:9200"
    xpack.monitoring.ui.container.elasticsearch.enabled: false
