
apiVersion: {{ .Chart.ApiVersion }}
kind: ConfigMap
metadata:
  name: kibana- {{- .Chart.AppVersion }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
data:
  kibana: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{ printf "http://%s.%s.svc.cluster.local:%d" .Values.global.services.elasticsearch.data .Values.global.namespace (int64 .Values.global.ports.elasticsearch.http) | quote }}
    xpack.monitoring.ui.container.elasticsearch.enabled: false
