apiVersion: apps/ {{- .Chart.ApiVersion }}
kind: Deployment
metadata:
  name: kibana-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range .Values.labels }}
      {{ . }}{{ end }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        {{- range .Values.labels }}
        {{ . }}{{ end }}
    spec:
      serviceAccountName: kibana-svc-acc
      containers:
      - name: kibana-container
        image: {{ .Values.images.kibana.repository -}} / {{- .Values.images.kibana.imageDigest }}
        imagePullPolicy: {{ .Values.images.kibana.pullPolicy }}
        ports:
        - containerPort: {{ .Values.global.ports.kibana.containerPort }}
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
          name: config
      volumes:
      - name: config
        configMap:
          name: kibana- {{- .Chart.AppVersion }}
          items:
          - key: kibana
            path: kibana.yml
