
apiVersion: {{ .Chart.ApiVersion }}
kind: ConfigMap
metadata:
  name: elasticsearch- {{- .Chart.AppVersion }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels.general }}
    {{ . }}{{ end }}
data: 
  master: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    discovery.zen:
      minimum_master_nodes: {{ .Values.elasticsearch.min_master }}
      ping.unicast.hosts: {{ .Values.global.services.elasticsearch.master -}} . {{- .Values.global.namespace -}} .svc.cluster.local: {{- .Values.global.ports.elasticsearch.transport }}
    network.host: _eth0_
    node:
      master: true
      data: false
      ingest: false
      ml: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
  data: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    discovery.zen:
      minimum_master_nodes: {{ .Values.elasticsearch.min_master }}
      ping.unicast.hosts: {{ .Values.global.services.elasticsearch.master -}} . {{- .Values.global.namespace -}} .svc.cluster.local: {{- .Values.global.ports.elasticsearch.transport }}
    network.host: 0.0.0.0
    node:
      master: false
      data: true
      ingest: true
      ml: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
