
apiVersion: apps/ {{- .Chart.ApiVersion }}
kind: Deployment
metadata:
  name: elasticsearch-deploy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels.master }}
    {{ . }}{{ end }}
spec:
  replicas: {{ .Values.replicaCount.master }}
  selector: 
    matchLabels: 
      {{- range .Values.labels.master }}
      {{ . }}{{ end }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        {{- range .Values.labels.master }}
        {{ . }}{{ end }}
    spec:
      serviceAccountName: elasticsearch-master-svc-acc
      initContainers:
      - name: elasticsearch-master-initcontainer
        image: {{ .Values.images.elasticsearch.repository -}} / {{- .Values.images.elasticsearch.imageDigest }}
        imagePullPolicy: {{ .Values.images.elasticsearch.pullPolicy }}
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-master-container
        image: {{ .Values.images.elasticsearch.repository -}} / {{- .Values.images.elasticsearch.imageDigest }}
        imagePullPolicy: {{ .Values.images.elasticsearch.pullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.global.ports.elasticsearch.transport }}
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: {{ .Values.global.ports.elasticsearch.transport }}
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          name: config
      volumes:
      - name: config
        configMap:
          name: elasticsearch- {{- .Chart.AppVersion }}
          items:
          - key: master
            path: elasticsearch.yml
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - namespaces:
            - {{ .Values.global.namespace }}
            labelSelector:
              matchLabels:
                {{- range .Values.labels.master }}
                {{ . }}{{ end }}
            topologyKey: kubernetes.io/hostname 
