
apiVersion: {{ .Chart.ApiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.services.elasticsearch.master }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels.master }}
    {{ . }}{{ end }}
spec:
  selector:
    {{- range .Values.labels.master }}
    {{ . }}{{ end }}
  ports:
  - name: transport
    port: {{ .Values.global.ports.elasticsearch.transport }}
    targetPort: {{ .Values.global.ports.elasticsearch.transport }}
    protocol: TCP
  type: {{ .Values.serviceType.master }}
  clusterIP: None
