global:
  services:
    elasticsearch:
      data: elasticsearch-data-svc
      master: elasticsearch-master-svc
    kibana: kibana-svc
    logstash: logstash-svc
  ports:
    elasticsearch:
      http: 9200
      transport: 9300
    kibana:
      nodePort: 31001
      containerPort: 5601
    logstash:
      browser: 5043
      controller: 5044
  namespace: log-monitoring
