
apiVersion: {{ .Chart.ApiVersion }}
kind: Service
metadata:
  name: {{ .Values.global.services.logstash }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
spec:
  ports:
  - name: logstash-svc-port-controller
    port: {{ .Values.global.ports.logstash.controller }}
    protocol: TCP
    targetPort: {{ .Values.global.ports.logstash.controller }}
  - name: logstash-svc-port-browser
    port: {{ .Values.global.ports.logstash.browser }}
    protocol: TCP
    targetPort: {{ .Values.global.ports.logstash.browser }}
  selector:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
  type: ClusterIP
