apiVersion: apps/ {{- .Chart.ApiVersion }}
kind: DaemonSet
metadata:
  name: logstash-daemon
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
spec:
  selector:
    matchLabels:
      {{- range .Values.labels }}
      {{ . }}{{ end }}
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      labels:
        {{- range .Values.labels }}
        {{ . }}{{ end }}
    spec:
      serviceAccountName: logstash-svc-acc
      containers:
      - name: logstash-container
        image: {{ .Values.images.logstash.repository -}} / {{- .Values.images.logstash.imageDigest }}
        imagePullPolicy: {{ .Values.images.logstash.pullPolicy }}
        ports:
        - containerPort: {{ .Values.global.ports.logstash.controller }}
          hostPort: {{ .Values.global.ports.logstash.controller }}
          protocol: TCP
        - containerPort: {{ .Values.global.ports.logstash.browser }}
          hostPort: {{ .Values.global.ports.logstash.browser }}
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          name: config
        - mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
          name: pipeline-config
        - mountPath: /usr/share/logstash/pipeline
          name: pipelines
      volumes:
      - name: config
        configMap:
          name: logstash- {{- .Chart.AppVersion }}
          items:
          - key: logstash
            path: logstash.yml
      - name: pipeline-config
        configMap:
          name: logstash- {{- .Chart.AppVersion }}
          items:
          - key: pipelines
            path: pipelines.yml
      - name: pipelines
        configMap:
          name: logstash- {{- .Chart.AppVersion }}
          items:
          - key: browser
            path: browser.conf
          - key: controller
            path: controller.conf

