
apiVersion: {{ .Chart.ApiVersion }}
kind: ConfigMap
metadata:
  name: logstash- {{- .Chart.AppVersion }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ . }}{{ end }}
data:
  logstash: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.url: {{ printf "http://%s.%s.svc.cluster.local:%d" .Values.global.services.elasticsearch.data .Values.global.namespace (int64 .Values.global.ports.elasticsearch.http) | quote }}

  pipelines: |
    - pipeline.id: browser
      path.config: "/usr/share/logstash/pipeline/browser.conf"
    - pipeline.id: controller
      path.config: "/usr/share/logstash/pipeline/controller.conf"

  browser: |-
    {{- include "pipelines.browser" . | indent 4 }}

  controller: |-
    {{- include "pipelines.controller" . | indent 4 }}
